server: 
  port: 8803
#当前eureka客户端（服务提供者）ID
spring:
  datasource:
    url: jdbc:mysql://192.168.1.112:3306/threebody?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    #客户端提供者在注册中心的名字
  application:
    name: eureka-client-provider-goods
    #redis缓存
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 60s  # 数据库连接超时时间，2.0 中该参数的类型为Duration，这里在配置的时候需要指明单位
    # 连接池配置，2.0中直接使用jedis或者lettuce配置连接池
    jedis:
      pool:
        # 最大空闲连接数
        max-idle: 500
        # 最小空闲连接数
        min-idle: 50
        # 等待可用连接的最大时间，负数为不限制
        max-wait:  -1s
        # 最大活跃连接数，负数为不限制
        max-active: -1
#配置thymeleaf
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
    encoding: UTF-8
    mode: HTML
#Eureka注册到服务中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.112:8761/eureka/    #注册中心地址
  instance: 
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
     
mybatis:
  mapper-locations: classpath:com/threebody/goods/mapper/xml/*.xml
  type-aliases-package: com.threebody.goods.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

