spring: 
  application:   
    name: eureka-client-customer-users
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
    encoding: UTF-8
    mode: HTML
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
    
server: 
  port: 8905
#Eureka注册到服务中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.112:8761/eureka/    #注册中心地址
  instance: 
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  
#feign自带断路器
feign: 
  hystrix:    enabled: false